@url = http://localhost:8080
@token =
###
POST {{url}}/auth/signup HTTP/1.1
Content-Type: application/json
Accept: application/json

{
	"username": "outragedline",
	"password": "outragedline"
}
###

POST {{url}}/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
	"username": "root",
	"password": "root"
}
###

POST {{url}}/courses HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
	"title": "teste",
	"description": "teste"
}
###


GET {{url}}/auth/verifyToken HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
